version: "3.9"

services:
  mysql:
#    platform: linux/amd64
    container_name: mysql5.7
    image: 'mysql:5.7'
    volumes:
      - did:/data/mysql
      - ./env/init.sql:/docker-entrypoint-initdb.d/init.sql # 초기 데이터 삽입 관련
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"

volumes:
  did: